// v5'te gerçek kullanıcı sistemi gelene kadar her şey bu hesaba bağlı.
export const DEMO_USER = {
  username: 'demo',
  email: 'demo@example.com',
}

export const DEMO_LIBRARY = [
  {
    name: 'Cyberpunk 2077',
    genre: 'RPG',
    platform: 'PC',
    releaseYear: 2020,
    status: 'playing',
    hours: 82,
    rating: 5,
    notes: 'Night City is worth the wait.',
    daysAgo: 1,
  },
  {
    name: 'Elden Ring',
    genre: 'RPG',
    platform: 'PC',
    releaseYear: 2022,
    status: 'completed',
    hours: 71,
    rating: 5,
    notes: 'Best boss design in years.',
    daysAgo: 3,
  },
  {
    name: 'Grand Theft Auto V',
    genre: 'Action',
    platform: 'PC',
    releaseYear: 2013,
    status: 'completed',
    hours: 156,
    rating: 5,
    notes: '',
    daysAgo: 6,
  },
  {
    name: 'Minecraft',
    genre: 'Sandbox',
    platform: 'PC',
    releaseYear: 2011,
    status: 'playing',
    hours: 320,
    rating: 4,
    notes: 'Still building the castle.',
    daysAgo: 8,
  },
  {
    name: 'The Witcher 3',
    genre: 'RPG',
    platform: 'PC',
    releaseYear: 2015,
    status: 'backlog',
    hours: 0,
    rating: 0,
    notes: '',
    daysAgo: 10,
  },
  {
    name: 'Hollow Knight',
    genre: 'Adventure',
    platform: 'Nintendo',
    releaseYear: 2017,
    status: 'backlog',
    hours: 2,
    rating: 0,
    notes: '',
    daysAgo: 12,
  },
  {
    name: 'Fallout 76',
    genre: 'Shooter',
    platform: 'PC',
    releaseYear: 2018,
    status: 'dropped',
    hours: 6,
    rating: 2,
    notes: 'Not for me.',
    daysAgo: 20,
  },
]
